import { expect, test } from '@playwright/test'
test('login by typing the inputs', async ({ page }) => {
  await page.goto('https://www.saucedemo.com/')
  await page.getByPlaceholder('Username').fill('standard_user')
  const passwordField = page.getByPlaceholder('Password')
  await passwordField.fill('secret_sauce')
  await passwordField.press('Enter')
  await expect(page).toHaveURL('https://www.saucedemo.com/inventory.html')
  await page.waitForTimeout(500)
  const cart = await page.locator('css=.shopping_cart_link').first()
  await expect(cart).toBeVisible()
  const products = await page.getByRole('list').first()
  await expect(products).toBeVisible()
  const jacketPage = await products.getByRole('listitem', { name: 'Jacket' }).first().getByRole('link').first().click()
  await jacketPage.getByRole('button', { name: 'Add to cart' }).first().click()
  await page.waitForTimeout(500)
  await expect(jacketPage.getByRole('button', { name: 'Remove' }).first()).toBeVisible()
  await page.goBack()
  await page.waitForTimeout(500)
  await expect(page).toHaveURL('https://www.saucedemo.com/inventory.html')
  await page.getByRole('list').first().getByRole('listitem', { name: 'Bike' }).first().getByRole('link').first().click()
  await page.getByRole('list').first().getByRole('listitem', { name: 'Bike' }).first().getByRole('button').first().click()
  await page.waitForTimeout(500)
  await page.locator('css=.shopping_cart_link').first().click()
  await page.waitForTimeout(500)
  await page.getByRole('button', { name: 'Checkout' }).first().click()
  await page.waitForTimeout(500)
  await page.getByPlaceholder('First Name').fill('John')
  await page.getByPlaceholder('Last Name').fill('Doe')
  await page.getByPlaceholder('Zip/Postal Code').fill('12345')
  await page.waitForTimeout(500)
  await page.getByRole('button', { name: 'Continue' }).first().click()
  await page.waitForTimeout(500)
  await page.getByRole('button', { name: 'Finish' }).first().click()
  await page.waitForTimeout(500)
  await expect(page).toHaveText('Thank you for your order!')
})
